[package]
name = "libp2p-webtransport"
version = "0.1.0"
edition = "2021"
rust-version.workspace = true
description = "TLS based QUIC transport implementation for libp2p"
repository = "https://github.com/libp2p/rust-libp2p"
license = "MIT"

[dependencies]
libp2p-core = { workspace = true }
libp2p-tls = { workspace = true }
libp2p-identity = { workspace = true, features = ["ed25519", "rand"] }
libp2p-noise = { workspace = true }
tokio = { workspace = true, default-features = false, features = ["net", "rt", "time"] }
futures = { workspace = true }
tracing = { workspace = true }
if-watch = { version = "3.2.0", features = ["tokio"] }
futures-timer = "3.0.3"
rustls = { version = "0.23.9", default-features = false }
thiserror = "1.0.61"
time = "0.3.36"
sha2 = "0.10.8"
quinn = { version = "0.11.2", default-features = false, features = ["rustls", "futures-io"] }
wtransport = "0.5.0"

[lints]
workspace = true
